// Copyright (c) 2026 Sidero Labs, Inc.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.

// generate-talos-ts emits TypeScript interfaces for Talos COSI resource specs.
//
// It reads the yaml struct tags from the actual Go types (the source of truth
// for the wire format, since COSI resources are YAML-serialised through the
// machinery) rather than the proto files in api/resource/definitions, which
// define the gRPC API surface and use different field names.
//
// Usage:
//
//	go run ./hack/generate-talos-ts [output-dir]
//
// output-dir defaults to frontend/src/api/talos.
package main

import (
	"encoding"
	"fmt"
	"net/netip"
	"os"
	"reflect"
	"strings"

	blockres "github.com/siderolabs/talos/pkg/machinery/resources/block"
	clusterres "github.com/siderolabs/talos/pkg/machinery/resources/cluster"
	hardwareres "github.com/siderolabs/talos/pkg/machinery/resources/hardware"
	k8sres "github.com/siderolabs/talos/pkg/machinery/resources/k8s"
	networkres "github.com/siderolabs/talos/pkg/machinery/resources/network"
	perfres "github.com/siderolabs/talos/pkg/machinery/resources/perf"
	runtimeres "github.com/siderolabs/talos/pkg/machinery/resources/runtime"
	v1alpha1res "github.com/siderolabs/talos/pkg/machinery/resources/v1alpha1"
)

var (
	textMarshalerType = reflect.TypeOf((*encoding.TextMarshaler)(nil)).Elem()
	netipAddrType     = reflect.TypeOf(netip.Addr{})
	netipPrefixType   = reflect.TypeOf(netip.Prefix{})
)

// outputFile groups related types into a single generated TypeScript file.
type outputFile struct {
	name  string
	roots []reflect.Type
}

// files defines what gets generated. Add entries here when the frontend needs
// types from a new Talos resource package. Transitive struct dependencies are
// collected automatically — only the "entry point" types need to be listed.
var files = []outputFile{
	{
		name: "perf.pb.ts",
		roots: []reflect.Type{
			reflect.TypeOf(perfres.CPUSpec{}),
			reflect.TypeOf(perfres.CPUStat{}),
			reflect.TypeOf(perfres.MemorySpec{}),
		},
	},
	{
		name: "block.pb.ts",
		roots: []reflect.Type{
			reflect.TypeOf(blockres.DiskSpec{}),
			reflect.TypeOf(blockres.DiscoveredVolumeSpec{}),
			reflect.TypeOf(blockres.VolumeStatusSpec{}),
		},
	},
	{
		name: "hardware.pb.ts",
		roots: []reflect.Type{
			reflect.TypeOf(hardwareres.PCIDeviceSpec{}),
			reflect.TypeOf(hardwareres.SystemInformationSpec{}),
		},
	},
	{
		name: "v1alpha1.pb.ts",
		roots: []reflect.Type{
			reflect.TypeOf(v1alpha1res.ServiceSpec{}),
		},
	},
	{
		name: "k8s.pb.ts",
		roots: []reflect.Type{
			reflect.TypeOf(k8sres.NodenameSpec{}),
		},
	},
	{
		name: "network.pb.ts",
		roots: []reflect.Type{
			reflect.TypeOf(networkres.NodeAddressSpec{}),
		},
	},
	{
		name: "runtime.pb.ts",
		roots: []reflect.Type{
			reflect.TypeOf(runtimeres.MachineStatusSpec{}),
		},
	},
	{
		name: "cluster.pb.ts",
		roots: []reflect.Type{
			reflect.TypeOf(clusterres.MemberSpec{}),
		},
	},
}

const fileHeader = `// This file is auto-generated by hack/generate-talos-ts. DO NOT EDIT.
//
// Source of truth: yaml struct tags on the Go types in
// github.com/siderolabs/talos/pkg/machinery/resources/
`

func main() {
	outDir := "frontend/src/api/talos"
	if len(os.Args) > 1 {
		outDir = os.Args[1]
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir %s: %v\n", outDir, err)
		os.Exit(1)
	}

	for _, f := range files {
		if err := generate(f, outDir); err != nil {
			fmt.Fprintf(os.Stderr, "generate %s: %v\n", f.name, err)
			os.Exit(1)
		}
	}
}

// generator collects struct types transitively and emits them in dependency order.
type generator struct {
	seen  map[reflect.Type]bool
	order []reflect.Type // types in emission order (dependencies before parents)
}

func newGenerator() *generator {
	return &generator{seen: make(map[reflect.Type]bool)}
}

// collect walks t and its struct-typed field dependencies, recording types in
// dependency-first order so the emitted file is always readable top-to-bottom.
func (g *generator) collect(t reflect.Type) {
	t = indirect(t)

	if t.Kind() == reflect.Slice {
		g.collect(t.Elem())

		return
	}

	if t.Kind() != reflect.Struct || !isTalosStruct(t) {
		return
	}

	if g.seen[t] {
		return
	}

	// Mark before recursing to break any cycles.
	g.seen[t] = true

	for i := range t.NumField() {
		f := t.Field(i)
		if yamlName(f) == "" {
			continue
		}

		g.collect(f.Type)
	}

	g.order = append(g.order, t)
}

func generate(f outputFile, outDir string) error {
	g := newGenerator()
	for _, root := range f.roots {
		g.collect(root)
	}

	var sb strings.Builder

	sb.WriteString(fileHeader)

	for _, t := range g.order {
		emitType(&sb, t, g)
	}

	path := outDir + "/" + f.name

	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

func emitType(sb *strings.Builder, t reflect.Type, g *generator) {
	sb.WriteString("\nexport type ")
	sb.WriteString(t.Name())
	sb.WriteString(" = {\n")

	for i := range t.NumField() {
		f := t.Field(i)

		name := yamlName(f)
		if name == "" {
			continue
		}

		tsType := toTS(f.Type, g)

		sb.WriteString("  ")
		sb.WriteString(name)
		sb.WriteString("?: ")
		sb.WriteString(tsType)
		sb.WriteString("\n")
	}

	sb.WriteString("}\n")
}

// toTS maps a Go type to its TypeScript counterpart.
func toTS(t reflect.Type, g *generator) string {
	// Unwrap pointer — all fields become optional in TypeScript anyway.
	t = indirect(t)

	// Slice: recurse into element type.
	if t.Kind() == reflect.Slice {
		elem := t.Elem()
		if elem.Kind() == reflect.Uint8 {
			return "string" // []byte → base64 string
		}

		return toTS(elem, g) + "[]"
	}

	// netip.Addr and netip.Prefix are structs but marshal as plain strings.
	if t == netipAddrType || t == netipPrefixType {
		return "string"
	}

	// Struct types from Talos machinery: emit a named TypeScript type.
	if t.Kind() == reflect.Struct && isTalosStruct(t) {
		if !g.seen[t] {
			g.collect(t)
		}

		return t.Name()
	}

	// Named user-defined types (enums, type aliases) —
	// check whether they serialise as strings via encoding.TextMarshaler.
	if t.PkgPath() != "" {
		if t.Implements(textMarshalerType) || reflect.PointerTo(t).Implements(textMarshalerType) {
			return "string"
		}

		// Fall through to primitive mapping using the underlying kind.
	}

	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	}

	return "unknown"
}

// isTalosStruct returns true for struct types defined in Talos machinery
// resource packages. The heuristic is presence of a protobuf struct tag,
// which all resource spec types carry.
func isTalosStruct(t reflect.Type) bool {
	if t.Kind() != reflect.Struct {
		return false
	}

	for i := range t.NumField() {
		if t.Field(i).Tag.Get("protobuf") != "" {
			return true
		}
	}

	return false
}

// indirect follows pointer types to their element.
func indirect(t reflect.Type) reflect.Type {
	for t.Kind() == reflect.Ptr {
		t = t.Elem()
	}

	return t
}

// yamlName extracts the field name from the yaml struct tag.
// Returns "" if the field should be skipped (no tag or tag "-").
func yamlName(f reflect.StructField) string {
	tag := f.Tag.Get("yaml")
	if tag == "" {
		return ""
	}

	name, _, _ := strings.Cut(tag, ",")
	if name == "-" {
		return ""
	}

	return name
}
