// This file is auto-generated by hack/generate-talos-ts. DO NOT EDIT.
//
// Source of truth: yaml struct tags on the Go types in
// github.com/siderolabs/talos/pkg/machinery/resources/

export type DiskSpec = {
  dev_path?: string
  size?: number
  pretty_size?: string
  io_size?: number
  sector_size?: number
  readonly?: boolean
  cdrom?: boolean
  model?: string
  serial?: string
  modalias?: string
  wwid?: string
  uuid?: string
  bus_path?: string
  sub_system?: string
  transport?: string
  rotational?: boolean
  secondary_disks?: string[]
  symlinks?: string[]
}

export type DiscoveredVolumeSpec = {
  dev_path?: string
  type?: string
  device_path?: string
  parent?: string
  parent_dev_path?: string
  offset?: number
  size?: number
  pretty_size?: string
  sector_size?: number
  io_size?: number
  name?: string
  uuid?: string
  label?: string
  block_size?: number
  filesystem_block_size?: number
  probed_size?: number
  partition_uuid?: string
  partition_type?: string
  partition_label?: string
  partition_index?: number
}

export type TPMEncryptionOptionsInfo = {
  pcrs?: number[]
  pubKeyPcrs?: number[]
}

export type ParameterSpec = {
  type?: string
  name?: string
  string?: string
  binary?: string
}

export type MountSpec = {
  targetPath?: string
  selinuxLabel?: string
  projectQuotaSupport?: boolean
  parentId?: string
  fileMode?: number
  uid?: number
  gid?: number
  recursiveRelabel?: boolean
  bindTarget?: string
  parameters?: ParameterSpec[]
  secure?: boolean
}

export type SymlinkProvisioningSpec = {
  symlinkTargetPath?: string
  force?: boolean
}

export type VolumeStatusSpec = {
  phase?: string
  preFailPhase?: string
  type?: string
  parentID?: string
  location?: string
  mountLocation?: string
  partitionIndex?: number
  parentLocation?: string
  uuid?: string
  partitionUUID?: string
  size?: number
  prettySize?: string
  filesystem?: string
  encryptionProvider?: string
  encryptionFailedSyncs?: string[]
  configuredEncryptionKeys?: string[]
  encryptionLockedToState?: boolean
  encryptionSlot?: number
  tpmEncryptionOptions?: TPMEncryptionOptionsInfo
  mountSpec?: MountSpec
  symlink?: SymlinkProvisioningSpec
  errorMessage?: string
}
