// This file is auto-generated by hack/generate-talos-ts. DO NOT EDIT.
//
// Source of truth: yaml struct tags on the Go types in
// github.com/siderolabs/talos/pkg/machinery/resources/

export type ControlPlane = {
  port?: number
}

export type MemberSpec = {
  nodeId?: string
  addresses?: string[]
  hostname?: string
  machineType?: string
  operatingSystem?: string
  controlPlane?: ControlPlane
}
