// This file is auto-generated by hack/generate-talos-ts. DO NOT EDIT.
//
// Source of truth: yaml struct tags on the Go types in
// github.com/siderolabs/talos/pkg/machinery/resources/

export type PCIDeviceSpec = {
  class?: string
  subclass?: string
  vendor?: string
  product?: string
  class_id?: string
  subclass_id?: string
  vendor_id?: string
  product_id?: string
  driver?: string
}

export type SystemInformationSpec = {
  manufacturer?: string
  productName?: string
  version?: string
  serialnumber?: string
  uuid?: string
  wakeUpType?: string
  skuNumber?: string
}
