// This file is auto-generated by hack/generate-talos-ts. DO NOT EDIT.
//
// Source of truth: yaml struct tags on the Go types in
// github.com/siderolabs/talos/pkg/machinery/resources/

export type UnmetCondition = {
  name?: string
  reason?: string
}

export type MachineStatusStatus = {
  ready?: boolean
  unmetConditions?: UnmetCondition[]
}

export type MachineStatusSpec = {
  stage?: string
  status?: MachineStatusStatus
}
